INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (1, 'Acre', 'AC', '12', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (2, 'Alagoas', 'AL', '27', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (3, 'Amapá', 'AP', '16', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (4, 'Amazonas', 'AM', '13', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (5, 'Bahia', 'BA', '29', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (6, 'Ceará', 'Ce', '23', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (7, 'Distrito Federal', 'DF', '53', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (8, 'Espírito Santo', 'ES', '32', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (9, 'Goiás', 'GO', '52', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (10, 'Maranhão', 'MA', '21', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (11, 'Mato Grosso do Sul', 'MS', '50', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (12, 'Mato Grosso', 'MT', '51', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (13, 'Minas Gerais', 'MS', '31', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (14, 'Paraná', 'PR', '41', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (15, 'Paraíba', 'PB', '25', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (16, 'Pará', 'PA', '15', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (17, 'Pernambuco', 'PE', '26', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (18, 'Piauí', 'PI', '22', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (19, 'Rio de Janeiro', 'RJ', '33', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (20, 'Rio Grande do Norte', 'RN', '24', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (21, 'Rio Grande do Sul', 'RS', '43', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (22, 'Rondônia', 'RO', '11', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (23, 'Roraima', 'RR', '14', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (24, 'Santa Catarina', 'SC', '42', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (25, 'Sergipe', 'SE', '28', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (26, 'São Paulo', 'SP', '35', 1);
INSERT INTO `estados` (id, nome, uf, codigo, pais_id) VALUES (27, 'Tocantins', 'TO', '17', 1);